const assert = require("assert");
const {
    $lcin_,
    $rcin_,
    $gen_lmost,
    $dlmost_,
    $gen_rmost,
    $drmost_,
    $lsib_of_fst_ance_having_lsib_,
    $rsib_of_fst_ance_having_rsib_,
} = require("../../edge");


var max_size= 4096
var vertexes = new Set([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
var eary = [
      2,  4099,  4100,
  12293, 12294,     7,
  24584, 24585, 24586,
  36875, 36876, 36877,
  36878, 36879, 36880
]


assert($lcin_ (max_size,eary,vertexes,1) === 0)
assert($lcin_ (max_size,eary,vertexes,2) === 0)
assert($lcin_ (max_size,eary,vertexes,3) === 0)
assert($lcin_ (max_size,eary,vertexes,4) === 0)
assert($lcin_ (max_size,eary,vertexes,5) === 0)
assert($lcin_ (max_size,eary,vertexes,6) === 0)
assert($lcin_ (max_size,eary,vertexes,7) === 0)
assert($lcin_ (max_size,eary,vertexes,8) === 4)
assert($lcin_ (max_size,eary,vertexes,9) === 0)
assert($lcin_ (max_size,eary,vertexes,10) === 0)
assert($lcin_ (max_size,eary,vertexes,11) === 0)
assert($lcin_ (max_size,eary,vertexes,12) === 0)
assert($lcin_ (max_size,eary,vertexes,13) === 0)
assert($lcin_ (max_size,eary,vertexes,14) === 0)
assert($lcin_ (max_size,eary,vertexes,15) === 0)
assert($lcin_ (max_size,eary,vertexes,16) === 0)

assert($rcin_ (max_size,eary,vertexes,1) === 0)
assert($rcin_ (max_size,eary,vertexes,2) === 0)
assert($rcin_ (max_size,eary,vertexes,3) === 0)
assert($rcin_ (max_size,eary,vertexes,4) === 8)
assert($rcin_ (max_size,eary,vertexes,5) === 0)
assert($rcin_ (max_size,eary,vertexes,6) === 0)
assert($rcin_ (max_size,eary,vertexes,7) === 0)
assert($rcin_ (max_size,eary,vertexes,8) === 0)
assert($rcin_ (max_size,eary,vertexes,9) === 0)
assert($rcin_ (max_size,eary,vertexes,10) === 0)
assert($rcin_ (max_size,eary,vertexes,11) === 0)
assert($rcin_ (max_size,eary,vertexes,12) === 0)
assert($rcin_ (max_size,eary,vertexes,13) === 0)
assert($rcin_ (max_size,eary,vertexes,14) === 0)
assert($rcin_ (max_size,eary,vertexes,15) === 0)
assert($rcin_ (max_size,eary,vertexes,16) === 0)


assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,1) === 0)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,2) === 0)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,3) === 0)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,4) === 0)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,5) === 3)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,6) === 3)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,7) === 0)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,8) === 2)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,9) === 2)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,10) === 2)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,11) === 9)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,12) === 9)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,13) === 9)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,14) === 9)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,15) === 9)
assert($lsib_of_fst_ance_having_lsib_ (max_size,eary,vertexes,16) === 9)

assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,1) === 0)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,2) === 0)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,3) === 7)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,4) === 7)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,5) === 7)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,6) === 7)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,7) === 0)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,8) === 0)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,9) === 0)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,10) === 0)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,11) === 0)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,12) === 0)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,13) === 0)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,14) === 0)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,15) === 0)
assert($rsib_of_fst_ance_having_rsib_ (max_size,eary,vertexes,16) === 0)


assert($dlmost_ (max_size,eary,vertexes,1) === 3)
assert($dlmost_ (max_size,eary,vertexes,2) === 3)
assert($dlmost_ (max_size,eary,vertexes,3) === 3)
assert($dlmost_ (max_size,eary,vertexes,4) === 5)
assert($dlmost_ (max_size,eary,vertexes,5) === 5)
assert($dlmost_ (max_size,eary,vertexes,6) === 6)
assert($dlmost_ (max_size,eary,vertexes,7) === 8)
assert($dlmost_ (max_size,eary,vertexes,8) === 8)
assert($dlmost_ (max_size,eary,vertexes,9) === 9)
assert($dlmost_ (max_size,eary,vertexes,10) === 11)
assert($dlmost_ (max_size,eary,vertexes,11) === 11)
assert($dlmost_ (max_size,eary,vertexes,12) === 12)
assert($dlmost_ (max_size,eary,vertexes,13) === 13)
assert($dlmost_ (max_size,eary,vertexes,14) === 14)
assert($dlmost_ (max_size,eary,vertexes,15) === 15)
assert($dlmost_ (max_size,eary,vertexes,16) === 16)


assert($drmost_ (max_size,eary,vertexes,1) === 16)
assert($drmost_ (max_size,eary,vertexes,2) === 6)
assert($drmost_ (max_size,eary,vertexes,3) === 3)
assert($drmost_ (max_size,eary,vertexes,4) === 6)
assert($drmost_ (max_size,eary,vertexes,5) === 5)
assert($drmost_ (max_size,eary,vertexes,6) === 6)
assert($drmost_ (max_size,eary,vertexes,7) === 16)
assert($drmost_ (max_size,eary,vertexes,8) === 8)
assert($drmost_ (max_size,eary,vertexes,9) === 9)
assert($drmost_ (max_size,eary,vertexes,10) === 16)
assert($drmost_ (max_size,eary,vertexes,11) === 11)
assert($drmost_ (max_size,eary,vertexes,12) === 12)
assert($drmost_ (max_size,eary,vertexes,13) === 13)
assert($drmost_ (max_size,eary,vertexes,14) === 14)
assert($drmost_ (max_size,eary,vertexes,15) === 15)
assert($drmost_ (max_size,eary,vertexes,16) === 16)


var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,1))
assert.deepStrictEqual(lmosts,[1,2,3])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,2))
assert.deepStrictEqual(lmosts,[2,3])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,3))
assert.deepStrictEqual(lmosts,[3])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,4))
assert.deepStrictEqual(lmosts,[4,5])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,5))
assert.deepStrictEqual(lmosts,[5])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,6))
assert.deepStrictEqual(lmosts,[6])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,7))
assert.deepStrictEqual(lmosts,[7,8])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,8))
assert.deepStrictEqual(lmosts,[8])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,9))
assert.deepStrictEqual(lmosts,[9])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,10))
assert.deepStrictEqual(lmosts,[10,11])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,11))
assert.deepStrictEqual(lmosts,[11])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,12))
assert.deepStrictEqual(lmosts,[12])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,13))
assert.deepStrictEqual(lmosts,[13])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,14))
assert.deepStrictEqual(lmosts,[14])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,15))
assert.deepStrictEqual(lmosts,[15])
var lmosts= Array.from($gen_lmost(max_size,eary,vertexes,16))
assert.deepStrictEqual(lmosts,[16])



var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,1))
assert.deepStrictEqual(rmosts,[1,7,10,16])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,2))
assert.deepStrictEqual(rmosts,[2,4,6])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,3))
assert.deepStrictEqual(rmosts,[3])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,4))
assert.deepStrictEqual(rmosts,[4,6])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,5))
assert.deepStrictEqual(rmosts,[5])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,6))
assert.deepStrictEqual(rmosts,[6])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,7))
assert.deepStrictEqual(rmosts,[7,10,16])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,8))
assert.deepStrictEqual(rmosts,[8])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,9))
assert.deepStrictEqual(rmosts,[9])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,10))
assert.deepStrictEqual(rmosts,[10,16])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,11))
assert.deepStrictEqual(rmosts,[11])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,12))
assert.deepStrictEqual(rmosts,[12])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,13))
assert.deepStrictEqual(rmosts,[13])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,14))
assert.deepStrictEqual(rmosts,[14])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,15))
assert.deepStrictEqual(rmosts,[15])
var rmosts= Array.from($gen_rmost(max_size,eary,vertexes,16))
assert.deepStrictEqual(rmosts,[16])
