const assert = require("assert");
const {
  $is_empty,            
  $is_root,
  $is_lstch,            
  $is_leaf,
  $is_fstch,            
  $is_lonely,
    $is_root_of,
    $is_parent_of,
    $is_ance_of,
    $is_inclusive_ance_of,
    $is_fstch_of,
    $is_lstch_of,
    $is_child_of,
    $is_des_of,
    $is_inclusive_des_of,
    $is_fsib_of,
    $is_rsib_of,
    $is_psib_of,
    $is_lsib_of,
    $is_sib_of,
    $is_inclusive_sib_of,
  $gen_fsib
} = require("../../edge");


var max_size= 4096
var vertexes = new Set([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
var eary = [
      2,  4099,  4100,
  12293, 12294,     7,
  24584, 24585, 24586,
  36875, 36876, 36877,
  36878, 36879, 36880
]


assert($is_empty (max_size,eary,vertexes,1) === false)
assert($is_empty (max_size,eary,vertexes,2) === false)
assert($is_empty (max_size,eary,vertexes,3) === false)
assert($is_empty (max_size,eary,vertexes,4) === false)
assert($is_empty (max_size,eary,vertexes,5) === false)
assert($is_empty (max_size,eary,vertexes,6) === false)
assert($is_empty (max_size,eary,vertexes,7) === false)
assert($is_empty (max_size,eary,vertexes,8) === false)
assert($is_empty (max_size,eary,vertexes,9) === false)
assert($is_empty (max_size,eary,vertexes,10) === false)
assert($is_empty (max_size,eary,vertexes,11) === false)
assert($is_empty (max_size,eary,vertexes,12) === false)
assert($is_empty (max_size,eary,vertexes,13) === false)
assert($is_empty (max_size,eary,vertexes,14) === false)
assert($is_empty (max_size,eary,vertexes,15) === false)
assert($is_empty (max_size,eary,vertexes,16) === false)


assert($is_root (max_size,eary,vertexes,1) === true)
assert($is_root (max_size,eary,vertexes,2) === false)
assert($is_root (max_size,eary,vertexes,3) === false)
assert($is_root (max_size,eary,vertexes,4) === false)
assert($is_root (max_size,eary,vertexes,5) === false)
assert($is_root (max_size,eary,vertexes,6) === false)
assert($is_root (max_size,eary,vertexes,7) === false)
assert($is_root (max_size,eary,vertexes,8) === false)
assert($is_root (max_size,eary,vertexes,9) === false)
assert($is_root (max_size,eary,vertexes,10) === false)
assert($is_root (max_size,eary,vertexes,11) === false)
assert($is_root (max_size,eary,vertexes,12) === false)
assert($is_root (max_size,eary,vertexes,13) === false)
assert($is_root (max_size,eary,vertexes,14) === false)
assert($is_root (max_size,eary,vertexes,15) === false)
assert($is_root (max_size,eary,vertexes,16) === false)

assert($is_fstch (max_size,eary,vertexes,1) === true)
assert($is_fstch (max_size,eary,vertexes,2) === true)
assert($is_fstch (max_size,eary,vertexes,3) === true)
assert($is_fstch (max_size,eary,vertexes,4) === false)
assert($is_fstch (max_size,eary,vertexes,5) === true)
assert($is_fstch (max_size,eary,vertexes,6) === false)
assert($is_fstch (max_size,eary,vertexes,7) === false)
assert($is_fstch (max_size,eary,vertexes,8) === true)
assert($is_fstch (max_size,eary,vertexes,9) === false)
assert($is_fstch (max_size,eary,vertexes,10) === false)
assert($is_fstch (max_size,eary,vertexes,11) === true)
assert($is_fstch (max_size,eary,vertexes,12) === false)
assert($is_fstch (max_size,eary,vertexes,13) === false)
assert($is_fstch (max_size,eary,vertexes,14) === false)
assert($is_fstch (max_size,eary,vertexes,15) === false)
assert($is_fstch (max_size,eary,vertexes,16) === false)


assert($is_lstch (max_size,eary,vertexes,1) === true)
assert($is_lstch (max_size,eary,vertexes,2) === false)
assert($is_lstch (max_size,eary,vertexes,3) === false)
assert($is_lstch (max_size,eary,vertexes,4) === true)
assert($is_lstch (max_size,eary,vertexes,5) === false)
assert($is_lstch (max_size,eary,vertexes,6) === true)
assert($is_lstch (max_size,eary,vertexes,7) === true)
assert($is_lstch (max_size,eary,vertexes,8) === false)
assert($is_lstch (max_size,eary,vertexes,9) === false)
assert($is_lstch (max_size,eary,vertexes,10) === true)
assert($is_lstch (max_size,eary,vertexes,11) === false)
assert($is_lstch (max_size,eary,vertexes,12) === false)
assert($is_lstch (max_size,eary,vertexes,13) === false)
assert($is_lstch (max_size,eary,vertexes,14) === false)
assert($is_lstch (max_size,eary,vertexes,15) === false)
assert($is_lstch (max_size,eary,vertexes,16) === true)


assert($is_leaf (max_size,eary,vertexes,1) === false)
assert($is_leaf (max_size,eary,vertexes,2) === false)
assert($is_leaf (max_size,eary,vertexes,3) === true)
assert($is_leaf (max_size,eary,vertexes,4) === false)
assert($is_leaf (max_size,eary,vertexes,5) === true)
assert($is_leaf (max_size,eary,vertexes,6) === true)
assert($is_leaf (max_size,eary,vertexes,7) === false)
assert($is_leaf (max_size,eary,vertexes,8) === true)
assert($is_leaf (max_size,eary,vertexes,9) === true)
assert($is_leaf (max_size,eary,vertexes,10) === false)
assert($is_leaf (max_size,eary,vertexes,11) === true)
assert($is_leaf (max_size,eary,vertexes,12) === true)
assert($is_leaf (max_size,eary,vertexes,13) === true)
assert($is_leaf (max_size,eary,vertexes,14) === true)
assert($is_leaf (max_size,eary,vertexes,15) === true)
assert($is_leaf (max_size,eary,vertexes,16) === true)

assert($is_lonely (max_size,eary,vertexes,1) === true)
assert($is_lonely (max_size,eary,vertexes,2) === false)
assert($is_lonely (max_size,eary,vertexes,3) === false)
assert($is_lonely (max_size,eary,vertexes,4) === false)
assert($is_lonely (max_size,eary,vertexes,5) === false)
assert($is_lonely (max_size,eary,vertexes,6) === false)
assert($is_lonely (max_size,eary,vertexes,7) === false)
assert($is_lonely (max_size,eary,vertexes,8) === false)
assert($is_lonely (max_size,eary,vertexes,9) === false)
assert($is_lonely (max_size,eary,vertexes,10) === false)
assert($is_lonely (max_size,eary,vertexes,11) === false)
assert($is_lonely (max_size,eary,vertexes,12) === false)
assert($is_lonely (max_size,eary,vertexes,13) === false)
assert($is_lonely (max_size,eary,vertexes,14) === false)
assert($is_lonely (max_size,eary,vertexes,15) === false)
assert($is_lonely (max_size,eary,vertexes,16) === false)


assert($is_root_of (max_size,eary,vertexes,1,1) === true)
assert($is_root_of (max_size,eary,vertexes,1,2) === true)
assert($is_root_of (max_size,eary,vertexes,1,3) === true)
assert($is_root_of (max_size,eary,vertexes,1,4) === true)
assert($is_root_of (max_size,eary,vertexes,1,5) === true)
assert($is_root_of (max_size,eary,vertexes,1,6) === true)
assert($is_root_of (max_size,eary,vertexes,1,7) === true)
assert($is_root_of (max_size,eary,vertexes,1,8) === true)
assert($is_root_of (max_size,eary,vertexes,1,9) === true)
assert($is_root_of (max_size,eary,vertexes,1,10) === true)
assert($is_root_of (max_size,eary,vertexes,1,11) === true)
assert($is_root_of (max_size,eary,vertexes,1,12) === true)
assert($is_root_of (max_size,eary,vertexes,1,13) === true)
assert($is_root_of (max_size,eary,vertexes,1,14) === true)
assert($is_root_of (max_size,eary,vertexes,1,15) === true)
assert($is_root_of (max_size,eary,vertexes,1,16) === true)

assert($is_parent_of (max_size,eary,vertexes,1,1) === false)
assert($is_parent_of (max_size,eary,vertexes,1,2) === true)
assert($is_parent_of (max_size,eary,vertexes,2,3) === true)
assert($is_parent_of (max_size,eary,vertexes,2,4) === true)
assert($is_parent_of (max_size,eary,vertexes,4,5) === true)
assert($is_parent_of (max_size,eary,vertexes,4,6) === true)
assert($is_parent_of (max_size,eary,vertexes,1,7) === true)
assert($is_parent_of (max_size,eary,vertexes,7,8) === true)
assert($is_parent_of (max_size,eary,vertexes,7,9) === true)
assert($is_parent_of (max_size,eary,vertexes,7,10) === true)
assert($is_parent_of (max_size,eary,vertexes,10,11) === true)
assert($is_parent_of (max_size,eary,vertexes,10,12) === true)
assert($is_parent_of (max_size,eary,vertexes,10,13) === true)
assert($is_parent_of (max_size,eary,vertexes,10,14) === true)
assert($is_parent_of (max_size,eary,vertexes,10,15) === true)
assert($is_parent_of (max_size,eary,vertexes,10,16) === true)


assert($is_ance_of (max_size,eary,vertexes,1,1) === false)
assert($is_ance_of (max_size,eary,vertexes,1,2) === true)
assert($is_ance_of (max_size,eary,vertexes,1,3) === true)
assert($is_ance_of (max_size,eary,vertexes,2,4) === true)
assert($is_ance_of (max_size,eary,vertexes,4,5) === true)
assert($is_ance_of (max_size,eary,vertexes,4,6) === true)
assert($is_ance_of (max_size,eary,vertexes,1,7) === true)
assert($is_ance_of (max_size,eary,vertexes,7,8) === true)
assert($is_ance_of (max_size,eary,vertexes,7,9) === true)
assert($is_ance_of (max_size,eary,vertexes,7,10) === true)
assert($is_ance_of (max_size,eary,vertexes,1,11) === true)
assert($is_ance_of (max_size,eary,vertexes,7,12) === true)
assert($is_ance_of (max_size,eary,vertexes,10,13) === true)
assert($is_ance_of (max_size,eary,vertexes,10,14) === true)
assert($is_ance_of (max_size,eary,vertexes,10,15) === true)
assert($is_ance_of (max_size,eary,vertexes,10,16) === true)

assert($is_inclusive_ance_of (max_size,eary,vertexes,1,1) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,1,2) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,1,3) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,2,4) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,4,5) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,4,6) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,1,7) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,7,8) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,7,9) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,7,10) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,1,11) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,7,12) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,10,13) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,10,14) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,10,15) === true)
assert($is_inclusive_ance_of (max_size,eary,vertexes,16,16) === true)

assert($is_inclusive_des_of (max_size,eary,vertexes,1,1) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,2,1) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,3,1) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,4,1) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,4,2) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,4,4) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,6,4) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,6,5) === false)
assert($is_inclusive_des_of (max_size,eary,vertexes,8,8) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,9,1) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,10,7) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,11,10) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,12,1) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,13,13) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,14,7) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,15,10) === true)
assert($is_inclusive_des_of (max_size,eary,vertexes,16,1) === true)

assert($is_des_of (max_size,eary,vertexes,1,1) === false)
assert($is_des_of (max_size,eary,vertexes,2,1) === true)
assert($is_des_of (max_size,eary,vertexes,3,1) === true)
assert($is_des_of (max_size,eary,vertexes,4,1) === true)
assert($is_des_of (max_size,eary,vertexes,4,2) === true)
assert($is_des_of (max_size,eary,vertexes,4,4) === false)
assert($is_des_of (max_size,eary,vertexes,6,4) === true)
assert($is_des_of (max_size,eary,vertexes,6,5) === false)
assert($is_des_of (max_size,eary,vertexes,8,8) === false)
assert($is_des_of (max_size,eary,vertexes,9,1) === true)
assert($is_des_of (max_size,eary,vertexes,10,7) === true)
assert($is_des_of (max_size,eary,vertexes,11,10) === true)
assert($is_des_of (max_size,eary,vertexes,12,1) === true)
assert($is_des_of (max_size,eary,vertexes,13,13) === false)
assert($is_des_of (max_size,eary,vertexes,14,7) === true)
assert($is_des_of (max_size,eary,vertexes,15,10) === true)
assert($is_des_of (max_size,eary,vertexes,16,1) === true)

assert($is_child_of (max_size,eary,vertexes,1,1) === false)
assert($is_child_of (max_size,eary,vertexes,2,1) === true)
assert($is_child_of (max_size,eary,vertexes,3,1) === false)
assert($is_child_of (max_size,eary,vertexes,4,1) === false)
assert($is_child_of (max_size,eary,vertexes,4,2) === true)
assert($is_child_of (max_size,eary,vertexes,4,4) === false)
assert($is_child_of (max_size,eary,vertexes,6,4) === true)
assert($is_child_of (max_size,eary,vertexes,6,5) === false)
assert($is_child_of (max_size,eary,vertexes,8,8) === false)
assert($is_child_of (max_size,eary,vertexes,9,1) === false)
assert($is_child_of (max_size,eary,vertexes,10,7) === true)
assert($is_child_of (max_size,eary,vertexes,11,10) === true)
assert($is_child_of (max_size,eary,vertexes,12,10) === true)
assert($is_child_of (max_size,eary,vertexes,13,13) === false)
assert($is_child_of (max_size,eary,vertexes,14,10) === true)
assert($is_child_of (max_size,eary,vertexes,15,10) === true)
assert($is_child_of (max_size,eary,vertexes,16,10) === true)


assert($is_fstch_of (max_size,eary,vertexes,1,1) === false)
assert($is_fstch_of (max_size,eary,vertexes,2,1) === true)
assert($is_fstch_of (max_size,eary,vertexes,3,1) === false)
assert($is_fstch_of (max_size,eary,vertexes,3,2) === true)
assert($is_fstch_of (max_size,eary,vertexes,4,3) === false)
assert($is_fstch_of (max_size,eary,vertexes,4,2) === false)
assert($is_fstch_of (max_size,eary,vertexes,5,4) === true)
assert($is_fstch_of (max_size,eary,vertexes,6,4) === false)
assert($is_fstch_of (max_size,eary,vertexes,6,5) === false)
assert($is_fstch_of (max_size,eary,vertexes,8,7) === true)
assert($is_fstch_of (max_size,eary,vertexes,9,1) === false)
assert($is_fstch_of (max_size,eary,vertexes,10,7) === false)
assert($is_fstch_of (max_size,eary,vertexes,11,10) === true)
assert($is_fstch_of (max_size,eary,vertexes,12,10) === false)
assert($is_fstch_of (max_size,eary,vertexes,13,13) === false)
assert($is_fstch_of (max_size,eary,vertexes,14,10) === false)
assert($is_fstch_of (max_size,eary,vertexes,15,10) === false)
assert($is_fstch_of (max_size,eary,vertexes,16,10) === false)


assert($is_lstch_of (max_size,eary,vertexes,1,1) === false)
assert($is_lstch_of (max_size,eary,vertexes,2,1) === false)
assert($is_lstch_of (max_size,eary,vertexes,3,1) === false)
assert($is_lstch_of (max_size,eary,vertexes,3,2) === false)
assert($is_lstch_of (max_size,eary,vertexes,4,3) === false)
assert($is_lstch_of (max_size,eary,vertexes,4,2) === true)
assert($is_lstch_of (max_size,eary,vertexes,5,4) === false)
assert($is_lstch_of (max_size,eary,vertexes,6,4) === true)
assert($is_lstch_of (max_size,eary,vertexes,6,5) === false)
assert($is_lstch_of (max_size,eary,vertexes,7,1) === true)
assert($is_lstch_of (max_size,eary,vertexes,8,7) === false)
assert($is_lstch_of (max_size,eary,vertexes,9,1) === false)
assert($is_lstch_of (max_size,eary,vertexes,10,7) === true)
assert($is_lstch_of (max_size,eary,vertexes,11,10) === false)
assert($is_lstch_of (max_size,eary,vertexes,12,10) === false)
assert($is_lstch_of (max_size,eary,vertexes,13,13) === false)
assert($is_lstch_of (max_size,eary,vertexes,14,10) === false)
assert($is_lstch_of (max_size,eary,vertexes,15,10) === false)
assert($is_lstch_of (max_size,eary,vertexes,16,10) === true)


assert($is_fsib_of (max_size,eary,vertexes,2,7) === false)
assert($is_fsib_of (max_size,eary,vertexes,7,2) === true)
assert($is_fsib_of (max_size,eary,vertexes,3,1) === false)
assert($is_fsib_of (max_size,eary,vertexes,3,2) === false)
assert($is_fsib_of (max_size,eary,vertexes,3,4) === false)
assert($is_fsib_of (max_size,eary,vertexes,4,3) === true)
assert($is_fsib_of (max_size,eary,vertexes,5,4) === false)
assert($is_fsib_of (max_size,eary,vertexes,5,6) === false)
assert($is_fsib_of (max_size,eary,vertexes,6,5) === true)
assert($is_fsib_of (max_size,eary,vertexes,7,1) === false)
assert($is_fsib_of (max_size,eary,vertexes,8,7) === false)
assert($is_fsib_of (max_size,eary,vertexes,8,9) === false)
assert($is_fsib_of (max_size,eary,vertexes,9,8) === true)
assert($is_fsib_of (max_size,eary,vertexes,9,10) === false)
assert($is_fsib_of (max_size,eary,vertexes,10,9) === true)
assert($is_fsib_of (max_size,eary,vertexes,11,12) === false)
assert($is_fsib_of (max_size,eary,vertexes,12,11) === true)
assert($is_fsib_of (max_size,eary,vertexes,13,11) === true)
assert($is_fsib_of (max_size,eary,vertexes,14,14) === false)
assert($is_fsib_of (max_size,eary,vertexes,15,14) === true)
assert($is_fsib_of (max_size,eary,vertexes,16,15) === true)


assert($is_rsib_of (max_size,eary,vertexes,1,1) === false)
assert($is_rsib_of (max_size,eary,vertexes,2,7) === false)
assert($is_rsib_of (max_size,eary,vertexes,7,2) === true)
assert($is_rsib_of (max_size,eary,vertexes,3,1) === false)
assert($is_rsib_of (max_size,eary,vertexes,3,2) === false)
assert($is_rsib_of (max_size,eary,vertexes,3,4) === false)
assert($is_rsib_of (max_size,eary,vertexes,4,3) === true)
assert($is_rsib_of (max_size,eary,vertexes,5,4) === false)
assert($is_rsib_of (max_size,eary,vertexes,5,6) === false)
assert($is_rsib_of (max_size,eary,vertexes,6,5) === true)
assert($is_rsib_of (max_size,eary,vertexes,7,1) === false)
assert($is_rsib_of (max_size,eary,vertexes,8,7) === false)
assert($is_rsib_of (max_size,eary,vertexes,8,9) === false)
assert($is_rsib_of (max_size,eary,vertexes,9,8) === true)
assert($is_rsib_of (max_size,eary,vertexes,9,10) === false)
assert($is_rsib_of (max_size,eary,vertexes,10,9) === true)
assert($is_rsib_of (max_size,eary,vertexes,11,12) === false)
assert($is_rsib_of (max_size,eary,vertexes,12,14) === false)
assert($is_rsib_of (max_size,eary,vertexes,12,13) === false)
assert($is_rsib_of (max_size,eary,vertexes,13,12) === true)
assert($is_rsib_of (max_size,eary,vertexes,14,14) === false)
assert($is_rsib_of (max_size,eary,vertexes,15,14) === true)
assert($is_rsib_of (max_size,eary,vertexes,16,15) === true)


assert($is_lsib_of (max_size,eary,vertexes,1,1) === false)
assert($is_lsib_of (max_size,eary,vertexes,2,7) === true)
assert($is_lsib_of (max_size,eary,vertexes,7,2) === false)
assert($is_lsib_of (max_size,eary,vertexes,3,1) === false)
assert($is_lsib_of (max_size,eary,vertexes,3,2) === false)
assert($is_lsib_of (max_size,eary,vertexes,3,4) === true)
assert($is_lsib_of (max_size,eary,vertexes,4,3) === false)
assert($is_lsib_of (max_size,eary,vertexes,5,4) === false)
assert($is_lsib_of (max_size,eary,vertexes,5,6) === true)
assert($is_lsib_of (max_size,eary,vertexes,6,5) === false)
assert($is_lsib_of (max_size,eary,vertexes,7,1) === false)
assert($is_lsib_of (max_size,eary,vertexes,8,7) === false)
assert($is_lsib_of (max_size,eary,vertexes,8,9) === true)
assert($is_lsib_of (max_size,eary,vertexes,9,8) === false)
assert($is_lsib_of (max_size,eary,vertexes,9,10) === true)
assert($is_lsib_of (max_size,eary,vertexes,10,9) === false)
assert($is_lsib_of (max_size,eary,vertexes,11,12) === true)
assert($is_lsib_of (max_size,eary,vertexes,12,14) === false)
assert($is_lsib_of (max_size,eary,vertexes,12,13) === true)
assert($is_lsib_of (max_size,eary,vertexes,14,14) === false)
assert($is_lsib_of (max_size,eary,vertexes,15,14) === false)
assert($is_lsib_of (max_size,eary,vertexes,15,16) === true)


assert($is_psib_of (max_size,eary,vertexes,1,1) === false)
assert($is_psib_of (max_size,eary,vertexes,2,7) === true)
assert($is_psib_of (max_size,eary,vertexes,7,2) === false)
assert($is_psib_of (max_size,eary,vertexes,3,1) === false)
assert($is_psib_of (max_size,eary,vertexes,3,2) === false)
assert($is_psib_of (max_size,eary,vertexes,3,4) === true)
assert($is_psib_of (max_size,eary,vertexes,4,3) === false)
assert($is_psib_of (max_size,eary,vertexes,5,4) === false)
assert($is_psib_of (max_size,eary,vertexes,5,6) === true)
assert($is_psib_of (max_size,eary,vertexes,6,5) === false)
assert($is_psib_of (max_size,eary,vertexes,7,1) === false)
assert($is_psib_of (max_size,eary,vertexes,8,7) === false)
assert($is_psib_of (max_size,eary,vertexes,8,9) === true)
assert($is_psib_of (max_size,eary,vertexes,9,8) === false)
assert($is_psib_of (max_size,eary,vertexes,9,10) === true)
assert($is_psib_of (max_size,eary,vertexes,10,9) === false)
assert($is_psib_of (max_size,eary,vertexes,11,12) === true)
assert($is_psib_of (max_size,eary,vertexes,12,14) === true)
assert($is_psib_of (max_size,eary,vertexes,12,13) === true)
assert($is_psib_of (max_size,eary,vertexes,13,12) === false)
assert($is_psib_of (max_size,eary,vertexes,14,14) === false)
assert($is_psib_of (max_size,eary,vertexes,15,14) === false)
assert($is_psib_of (max_size,eary,vertexes,16,15) === false)



assert($is_sib_of (max_size,eary,vertexes,1,1) === false)
assert($is_sib_of (max_size,eary,vertexes,2,7) === true)
assert($is_sib_of (max_size,eary,vertexes,7,2) === true)
assert($is_sib_of (max_size,eary,vertexes,3,1) === false)
assert($is_sib_of (max_size,eary,vertexes,3,2) === false)
assert($is_sib_of (max_size,eary,vertexes,3,4) === true)
assert($is_sib_of (max_size,eary,vertexes,4,3) === true)
assert($is_sib_of (max_size,eary,vertexes,5,4) === false)
assert($is_sib_of (max_size,eary,vertexes,5,6) === true)
assert($is_sib_of (max_size,eary,vertexes,6,5) === true)
assert($is_sib_of (max_size,eary,vertexes,7,1) === false)
assert($is_sib_of (max_size,eary,vertexes,8,7) === false)
assert($is_sib_of (max_size,eary,vertexes,8,9) === true)
assert($is_sib_of (max_size,eary,vertexes,9,8) === true)
assert($is_sib_of (max_size,eary,vertexes,9,10) === true)
assert($is_sib_of (max_size,eary,vertexes,10,9) === true)
assert($is_sib_of (max_size,eary,vertexes,11,12) === true)
assert($is_sib_of (max_size,eary,vertexes,12,14) === true)
assert($is_sib_of (max_size,eary,vertexes,12,13) === true)
assert($is_sib_of (max_size,eary,vertexes,13,12) === true)
assert($is_sib_of (max_size,eary,vertexes,14,14) === false)
assert($is_sib_of (max_size,eary,vertexes,15,14) === true)
assert($is_sib_of (max_size,eary,vertexes,16,16) === false)

assert($is_inclusive_sib_of (max_size,eary,vertexes,1,1) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,2,7) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,7,2) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,3,1) === false)
assert($is_inclusive_sib_of (max_size,eary,vertexes,3,2) === false)
assert($is_inclusive_sib_of (max_size,eary,vertexes,3,4) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,4,3) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,5,4) === false)
assert($is_inclusive_sib_of (max_size,eary,vertexes,5,6) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,6,5) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,7,1) === false)
assert($is_inclusive_sib_of (max_size,eary,vertexes,8,7) === false)
assert($is_inclusive_sib_of (max_size,eary,vertexes,8,9) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,9,8) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,9,10) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,10,9) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,11,12) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,12,14) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,12,13) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,13,12) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,14,14) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,15,14) === true)
assert($is_inclusive_sib_of (max_size,eary,vertexes,16,16) === true)




